'use client'

import { useEffect, useState } from 'react'
import Link from 'next/link'
import { db, BlogPost, BlogCategory } from '@/lib/supabase/client'
import { PageHeader } from '@/components/cms'
import Badge from '@/components/ui/Badge'
import Button from '@/components/ui/Button'
import { 
  Plus,
  Search,
  Filter,
  RefreshCw,
  Eye,
  Edit,
  Trash2,
  Calendar,
  Clock,
  TrendingUp,
  FileText,
  Sparkles,
  MoreVertical,
  ArrowUpRight,
  Archive,
  Send,
} from 'lucide-react'
import { formatDateTime } from '@/lib/utils/helpers'

type BlogPostWithCategory = BlogPost & {
  blog_categories: Pick<BlogCategory, 'id' | 'name' | 'slug' | 'color'> | null
}

export default function BlogPage() {
  const [posts, setPosts] = useState<BlogPostWithCategory[]>([])
  const [categories, setCategories] = useState<BlogCategory[]>([])
  const [loading, setLoading] = useState(true)
  const [refreshing, setRefreshing] = useState(false)
  const [totalCount, setTotalCount] = useState(0)
  const [filters, setFilters] = useState({
    status: '',
    category_id: '',
    search: '',
  })
  const [stats, setStats] = useState({
    total: 0,
    published: 0,
    draft: 0,
    scheduled: 0,
    autoGenerated: 0,
  })

  useEffect(() => {
    fetchData()
  }, [filters.status, filters.category_id])

  const fetchData = async (isRefresh = false) => {
    if (isRefresh) setRefreshing(true)
    else setLoading(true)

    try {
      const [postsResult, categoriesResult] = await Promise.all([
        db.blogPosts.getAll({
          status: filters.status || undefined,
          category_id: filters.category_id || undefined,
          limit: 50,
        }),
        db.blogCategories.getAll(true),
      ])

      setPosts(postsResult.data as BlogPostWithCategory[])
      setTotalCount(postsResult.count || 0)
      setCategories(categoriesResult)

      // Calculate stats from all posts
      const allPosts = await db.blogPosts.getAll({ limit: 1000 })
      const allData = allPosts.data || []
      setStats({
        total: allData.length,
        published: allData.filter(p => p.status === 'published').length,
        draft: allData.filter(p => p.status === 'draft').length,
        scheduled: allData.filter(p => p.status === 'scheduled').length,
        autoGenerated: allData.filter(p => p.is_auto_generated).length,
      })
    } catch (error) {
      console.error('Error fetching blog data:', error)
    } finally {
      setLoading(false)
      setRefreshing(false)
    }
  }

  const handlePublish = async (id: string) => {
    try {
      await db.blogPosts.publish(id)
      fetchData(true)
    } catch (error) {
      console.error('Error publishing post:', error)
    }
  }

  const handleArchive = async (id: string) => {
    try {
      await db.blogPosts.archive(id)
      fetchData(true)
    } catch (error) {
      console.error('Error archiving post:', error)
    }
  }

  const handleDelete = async (id: string) => {
    if (!confirm('Are you sure you want to delete this post? This action cannot be undone.')) return
    try {
      await db.blogPosts.delete(id)
      fetchData(true)
    } catch (error) {
      console.error('Error deleting post:', error)
    }
  }

  const getStatusBadge = (status: string | null) => {
    const statusConfig: Record<string, { label: string; variant: 'default' | 'success' | 'warning' | 'info' | 'error' }> = {
      draft: { label: 'Draft', variant: 'default' },
      scheduled: { label: 'Scheduled', variant: 'info' },
      published: { label: 'Published', variant: 'success' },
      archived: { label: 'Archived', variant: 'warning' },
    }
    const config = statusConfig[status || 'draft'] || { label: status || 'Unknown', variant: 'default' as const }
    return <Badge variant={config.variant}>{config.label}</Badge>
  }

  if (loading) {
    return (
      <div className="flex items-center justify-center min-h-[60vh]">
        <div className="text-center">
          <div className="w-12 h-12 border-4 border-primary-200 border-t-primary-600 rounded-full animate-spin mx-auto mb-4"></div>
          <p className="text-neutral-600 font-medium">Loading blog posts...</p>
        </div>
      </div>
    )
  }

  return (
    <div className="max-w-7xl mx-auto">
      <PageHeader
        title="Blog Posts"
        description="Manage blog content, market analysis, and industry insights"
        actions={
          <>
            <Button 
              variant="outline" 
              size="sm"
              onClick={() => fetchData(true)}
              disabled={refreshing}
            >
              <RefreshCw size={16} className={refreshing ? 'animate-spin' : ''} />
              Refresh
            </Button>
            <Link href="/cms/dashboard/blog/categories">
              <Button variant="outline" size="sm">
                <FileText size={16} />
                Categories
              </Button>
            </Link>
            <Link href="/cms/dashboard/blog/new">
              <Button size="sm">
                <Plus size={16} />
                New Post
              </Button>
            </Link>
          </>
        }
      />

      {/* Stats Grid */}
      <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-5 gap-4 mb-8">
        <div className="bg-white rounded-xl border border-neutral-200 p-4">
          <div className="flex items-center gap-3">
            <div className="p-2 bg-blue-50 rounded-lg">
              <FileText size={18} className="text-blue-600" />
            </div>
            <div>
              <p className="text-2xl font-bold text-neutral-900">{stats.total}</p>
              <p className="text-sm text-neutral-500">Total Posts</p>
            </div>
          </div>
        </div>
        <div className="bg-white rounded-xl border border-neutral-200 p-4">
          <div className="flex items-center gap-3">
            <div className="p-2 bg-green-50 rounded-lg">
              <TrendingUp size={18} className="text-green-600" />
            </div>
            <div>
              <p className="text-2xl font-bold text-neutral-900">{stats.published}</p>
              <p className="text-sm text-neutral-500">Published</p>
            </div>
          </div>
        </div>
        <div className="bg-white rounded-xl border border-neutral-200 p-4">
          <div className="flex items-center gap-3">
            <div className="p-2 bg-neutral-100 rounded-lg">
              <Edit size={18} className="text-neutral-600" />
            </div>
            <div>
              <p className="text-2xl font-bold text-neutral-900">{stats.draft}</p>
              <p className="text-sm text-neutral-500">Drafts</p>
            </div>
          </div>
        </div>
        <div className="bg-white rounded-xl border border-neutral-200 p-4">
          <div className="flex items-center gap-3">
            <div className="p-2 bg-purple-50 rounded-lg">
              <Clock size={18} className="text-purple-600" />
            </div>
            <div>
              <p className="text-2xl font-bold text-neutral-900">{stats.scheduled}</p>
              <p className="text-sm text-neutral-500">Scheduled</p>
            </div>
          </div>
        </div>
        <div className="bg-white rounded-xl border border-neutral-200 p-4">
          <div className="flex items-center gap-3">
            <div className="p-2 bg-amber-50 rounded-lg">
              <Sparkles size={18} className="text-amber-600" />
            </div>
            <div>
              <p className="text-2xl font-bold text-neutral-900">{stats.autoGenerated}</p>
              <p className="text-sm text-neutral-500">Auto-Generated</p>
            </div>
          </div>
        </div>
      </div>

      {/* Filters */}
      <div className="bg-white rounded-xl border border-neutral-200 p-4 mb-6">
        <div className="flex flex-wrap items-center gap-4">
          <div className="flex-1 min-w-[200px]">
            <div className="relative">
              <Search size={18} className="absolute left-3 top-1/2 -translate-y-1/2 text-neutral-400" />
              <input
                type="text"
                placeholder="Search posts..."
                value={filters.search}
                onChange={(e) => setFilters(prev => ({ ...prev, search: e.target.value }))}
                className="w-full pl-10 pr-4 py-2 border border-neutral-200 rounded-lg focus:ring-2 focus:ring-primary-500 focus:border-transparent"
              />
            </div>
          </div>
          <select
            value={filters.status}
            onChange={(e) => setFilters(prev => ({ ...prev, status: e.target.value }))}
            className="px-4 py-2 border border-neutral-200 rounded-lg focus:ring-2 focus:ring-primary-500 focus:border-transparent"
          >
            <option value="">All Status</option>
            <option value="draft">Draft</option>
            <option value="scheduled">Scheduled</option>
            <option value="published">Published</option>
            <option value="archived">Archived</option>
          </select>
          <select
            value={filters.category_id}
            onChange={(e) => setFilters(prev => ({ ...prev, category_id: e.target.value }))}
            className="px-4 py-2 border border-neutral-200 rounded-lg focus:ring-2 focus:ring-primary-500 focus:border-transparent"
          >
            <option value="">All Categories</option>
            {categories.map(cat => (
              <option key={cat.id} value={cat.id}>{cat.name}</option>
            ))}
          </select>
        </div>
      </div>

      {/* Posts Table */}
      <div className="bg-white rounded-2xl border border-neutral-200 overflow-hidden">
        <div className="px-6 py-4 border-b border-neutral-200">
          <div className="flex items-center justify-between">
            <div>
              <h2 className="text-lg font-semibold text-neutral-900">All Posts</h2>
              <p className="text-sm text-neutral-500">{totalCount} total posts</p>
            </div>
          </div>
        </div>

        {posts.length === 0 ? (
          <div className="px-6 py-16 text-center">
            <div className="w-16 h-16 bg-neutral-100 rounded-2xl flex items-center justify-center mx-auto mb-4">
              <FileText size={32} className="text-neutral-400" />
            </div>
            <h3 className="text-lg font-semibold text-neutral-900 mb-2">No posts found</h3>
            <p className="text-neutral-500 max-w-sm mx-auto mb-4">
              {filters.status || filters.category_id 
                ? 'No posts match your current filters. Try adjusting your filters.'
                : 'Get started by creating your first blog post.'}
            </p>
            <Link href="/cms/dashboard/blog/new">
              <Button size="sm">
                <Plus size={16} />
                Create Post
              </Button>
            </Link>
          </div>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full">
              <thead>
                <tr className="bg-neutral-50">
                  <th className="px-6 py-3 text-left text-xs font-semibold text-neutral-500 uppercase tracking-wider">
                    Post
                  </th>
                  <th className="px-6 py-3 text-left text-xs font-semibold text-neutral-500 uppercase tracking-wider">
                    Category
                  </th>
                  <th className="px-6 py-3 text-left text-xs font-semibold text-neutral-500 uppercase tracking-wider">
                    Status
                  </th>
                  <th className="px-6 py-3 text-left text-xs font-semibold text-neutral-500 uppercase tracking-wider">
                    Views
                  </th>
                  <th className="px-6 py-3 text-left text-xs font-semibold text-neutral-500 uppercase tracking-wider">
                    Date
                  </th>
                  <th className="px-6 py-3 text-right text-xs font-semibold text-neutral-500 uppercase tracking-wider">
                    Actions
                  </th>
                </tr>
              </thead>
              <tbody className="divide-y divide-neutral-200">
                {posts.map((post) => (
                  <tr key={post.id} className="hover:bg-neutral-50 transition-colors">
                    <td className="px-6 py-4">
                      <div className="flex items-start gap-3">
                        {post.featured_image ? (
                          <img 
                            src={post.featured_image} 
                            alt="" 
                            className="w-12 h-12 rounded-lg object-cover shrink-0"
                          />
                        ) : (
                          <div className="w-12 h-12 bg-neutral-100 rounded-lg flex items-center justify-center shrink-0">
                            <FileText size={20} className="text-neutral-400" />
                          </div>
                        )}
                        <div className="min-w-0">
                          <div className="flex items-center gap-2">
                            <p className="font-medium text-neutral-900 truncate max-w-[300px]">
                              {post.title}
                            </p>
                            {post.is_auto_generated && (
                              <span className="shrink-0 px-1.5 py-0.5 bg-amber-100 text-amber-700 text-xs rounded">
                                Auto
                              </span>
                            )}
                          </div>
                          <p className="text-sm text-neutral-500 truncate max-w-[300px]">
                            {post.excerpt || 'No excerpt'}
                          </p>
                        </div>
                      </div>
                    </td>
                    <td className="px-6 py-4">
                      {post.blog_categories ? (
                        <span 
                          className="inline-flex items-center px-2.5 py-1 rounded-full text-xs font-medium"
                          style={{
                            backgroundColor: `${post.blog_categories.color || '#6B7280'}20`,
                            color: post.blog_categories.color || '#6B7280',
                          }}
                        >
                          {post.blog_categories.name}
                        </span>
                      ) : (
                        <span className="text-neutral-400 text-sm">Uncategorized</span>
                      )}
                    </td>
                    <td className="px-6 py-4">
                      {getStatusBadge(post.status)}
                    </td>
                    <td className="px-6 py-4">
                      <div className="flex items-center gap-1.5 text-neutral-600">
                        <Eye size={14} />
                        <span className="text-sm">{post.view_count || 0}</span>
                      </div>
                    </td>
                    <td className="px-6 py-4">
                      <div className="flex items-center gap-2 text-neutral-500">
                        <Calendar size={14} />
                        <span className="text-sm">
                          {post.published_at 
                            ? formatDateTime(post.published_at)
                            : formatDateTime(post.created_at)}
                        </span>
                      </div>
                    </td>
                    <td className="px-6 py-4 text-right">
                      <div className="flex items-center justify-end gap-1">
                        {post.status === 'published' && (
                          <a 
                            href={`/blog/${post.slug}`} 
                            target="_blank"
                            className="p-2 text-neutral-500 hover:text-primary-600 hover:bg-primary-50 rounded-lg transition-colors"
                            title="View Live"
                          >
                            <ArrowUpRight size={18} />
                          </a>
                        )}
                        <Link href={`/cms/dashboard/blog/${post.id}`}>
                          <button className="p-2 text-neutral-500 hover:text-primary-600 hover:bg-primary-50 rounded-lg transition-colors">
                            <Edit size={18} />
                          </button>
                        </Link>
                        {post.status === 'draft' && (
                          <button 
                            onClick={() => handlePublish(post.id)}
                            className="p-2 text-neutral-500 hover:text-green-600 hover:bg-green-50 rounded-lg transition-colors"
                            title="Publish"
                          >
                            <Send size={18} />
                          </button>
                        )}
                        {post.status === 'published' && (
                          <button 
                            onClick={() => handleArchive(post.id)}
                            className="p-2 text-neutral-500 hover:text-orange-600 hover:bg-orange-50 rounded-lg transition-colors"
                            title="Archive"
                          >
                            <Archive size={18} />
                          </button>
                        )}
                        <button 
                          onClick={() => handleDelete(post.id)}
                          className="p-2 text-neutral-500 hover:text-red-600 hover:bg-red-50 rounded-lg transition-colors"
                          title="Delete"
                        >
                          <Trash2 size={18} />
                        </button>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </div>
  )
}
